apiVersion: v1
kind: Service
metadata:
  name: service # Service Name
spec:
  selector:
    app: split-wise # Application Name
  ports:
    - protocol: TCP # Transmission Control Protocol
      port: 80
      targetPort: 8080
  type: NodePort
  